# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/display_decoder_segment_e_0_0.xci
# IP: The module: 'display_decoder_segment_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_3/segment_e_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_3 || ORIG_REF_NAME==segment_e_xup_inv_0_3} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_2/segment_e_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_2 || ORIG_REF_NAME==segment_e_xup_inv_0_2} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_1/segment_e_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_1 || ORIG_REF_NAME==segment_e_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_0/segment_e_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_0 || ORIG_REF_NAME==segment_e_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_or2_0_0/segment_e_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_or2_0_0 || ORIG_REF_NAME==segment_e_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_and2_0_0/segment_e_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_and2_0_0 || ORIG_REF_NAME==segment_e_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_decoder_segment_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/display_decoder_segment_e_0_0.xci
# IP: The module: 'display_decoder_segment_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_3/segment_e_xup_inv_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_3 || ORIG_REF_NAME==segment_e_xup_inv_0_3} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_2/segment_e_xup_inv_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_2 || ORIG_REF_NAME==segment_e_xup_inv_0_2} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_1/segment_e_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_1 || ORIG_REF_NAME==segment_e_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_inv_0_0/segment_e_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_inv_0_0 || ORIG_REF_NAME==segment_e_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_or2_0_0/segment_e_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_or2_0_0 || ORIG_REF_NAME==segment_e_xup_or2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_xup_and2_0_0/segment_e_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==segment_e_xup_and2_0_0 || ORIG_REF_NAME==segment_e_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_decoder_segment_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
