@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 14 03:41:34 -0700 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim Output_Sim_behav -key {Behavioral:sim_1:Functional:Output_Sim} -tclbatch Output_Sim.tcl -protoinst "protoinst_files/segment_g.protoinst" -protoinst "protoinst_files/segment_f.protoinst" -protoinst "protoinst_files/segment_e.protoinst" -protoinst "protoinst_files/segment_d.protoinst" -protoinst "protoinst_files/segment_c.protoinst" -protoinst "protoinst_files/segment_b.protoinst" -protoinst "protoinst_files/segment_a.protoinst" -log simulate.log"
call xsim  Output_Sim_behav -key {Behavioral:sim_1:Functional:Output_Sim} -tclbatch Output_Sim.tcl -protoinst "protoinst_files/segment_g.protoinst" -protoinst "protoinst_files/segment_f.protoinst" -protoinst "protoinst_files/segment_e.protoinst" -protoinst "protoinst_files/segment_d.protoinst" -protoinst "protoinst_files/segment_c.protoinst" -protoinst "protoinst_files/segment_b.protoinst" -protoinst "protoinst_files/segment_a.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
