# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache {C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/.Xil/Vivado-11540-StefanDesktop/incrSyn}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
set_msg_config  -id {IP_Flow 19-4995}  -suppress 
set_msg_config  -id {Common 17-576}  -string {{WARNING: [Common 17-576] 'use_project_ipc' is deprecated. This option is deprecated and no longer used.}}  -suppress 
set_msg_config  -id {Constraints 18-5210}  -string {{WARNING: [Constraints 18-5210] No constraints selected for write.
Resolution: This message can indicate that there are no constraints for the design, or it can indicate that the used_in flags are set such that the constraints are ignored. This later case is used when running synth_design to not write synthesis constraints to the resulting checkpoint. Instead, project constraints are read when the synthesized design is opened.}}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/XUP_LIB}} [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {{C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/hdl/display_decoder_wrapper.v}}
add_files {{C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/display_decoder.bd}}
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_a_0_0/src/segment_a_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_b_0_0/src/segment_b_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_c_0_0/src/segment_c_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_d_0_0/src/segment_d_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_e_0_0/src/segment_e_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_f_0_0/src/segment_f_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_segment_g_0_0/src/segment_g_ooc.xdc}}]
set_property used_in_implementation false [get_files -all {{c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/src/my_xdc.xdc}}]
set_property used_in_implementation false [get_files -all {{C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/display_decoder_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/my_xdc.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/my_xdc.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top display_decoder_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef display_decoder_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file display_decoder_wrapper_utilization_synth.rpt -pb display_decoder_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
