# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/my_xdc.xdc

# Block Designs: bd/display_decoder/display_decoder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder || ORIG_REF_NAME==display_decoder} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_a_0_0/display_decoder_segment_a_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_a_0_0 || ORIG_REF_NAME==display_decoder_segment_a_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_b_0_0/display_decoder_segment_b_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_b_0_0 || ORIG_REF_NAME==display_decoder_segment_b_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_c_0_0/display_decoder_segment_c_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_c_0_0 || ORIG_REF_NAME==display_decoder_segment_c_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_d_0_0/display_decoder_segment_d_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_d_0_0 || ORIG_REF_NAME==display_decoder_segment_d_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_e_0_0/display_decoder_segment_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_e_0_0 || ORIG_REF_NAME==display_decoder_segment_e_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_f_0_0/display_decoder_segment_f_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_f_0_0 || ORIG_REF_NAME==display_decoder_segment_f_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_segment_g_0_0/display_decoder_segment_g_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_segment_g_0_0 || ORIG_REF_NAME==display_decoder_segment_g_0_0} -quiet] -quiet

# IP: bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/display_decoder_Segment_LED_Interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==display_decoder_Segment_LED_Interface_0_0 || ORIG_REF_NAME==display_decoder_Segment_LED_Interface_0_0} -quiet] -quiet

# XDC: bd/display_decoder/display_decoder_ooc.xdc
