# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/design_2_design_1_1_1.xci
# IP: The module: 'design_2_design_1_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_and2_1_0/design_1_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_1_0 || ORIG_REF_NAME==design_1_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_xor2_0_0/design_1_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_0 || ORIG_REF_NAME==design_1_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_xor2_1_0/design_1_xup_xor2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_1_0 || ORIG_REF_NAME==design_1_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_or2_0_0/design_1_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_0 || ORIG_REF_NAME==design_1_xup_or2_0_0} -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_design_1_1_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/design_2_design_1_1_1.xci
# IP: The module: 'design_2_design_1_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_and2_1_0/design_1_xup_and2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_1_0 || ORIG_REF_NAME==design_1_xup_and2_1_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_xor2_0_0/design_1_xup_xor2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_0_0 || ORIG_REF_NAME==design_1_xup_xor2_0_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_xor2_1_0/design_1_xup_xor2_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_xor2_1_0 || ORIG_REF_NAME==design_1_xup_xor2_1_0} -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_xup_or2_0_0/design_1_xup_or2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_0 || ORIG_REF_NAME==design_1_xup_or2_0_0} -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Marth_Lab1/CSE320_Marth_Lab1.srcs/sources_1/bd/design_2/ip/design_2_design_1_1_1/src/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_2_design_1_1_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
