# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_tutorial5/CSE320_tutorial5.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
