# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/display_decoder_Segment_LED_Interface_0_0.xci
# IP: The module: 'display_decoder_Segment_LED_Interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/src/my_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_decoder_Segment_LED_Interface_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/display_decoder_Segment_LED_Interface_0_0.xci
# IP: The module: 'display_decoder_Segment_LED_Interface_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/Labs_New/CSE320_Lab2/CSE320_Lab2.srcs/sources_1/bd/display_decoder/ip/display_decoder_Segment_LED_Interface_0_0/src/my_xdc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_decoder_Segment_LED_Interface_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
