# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/stefa/iCloudDrive/ASU/Spring 2020/CSE_320/CSE320_Tutorial1/CSE320_tutorial1_source/tutorial_nexys4_ddr.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_inv_1_0/design_1_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_1_0 || ORIG_REF_NAME==design_1_xup_inv_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xup_or2_0_0/design_1_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_or2_0_0 || ORIG_REF_NAME==design_1_xup_or2_0_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
