# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/lab1_Nexys4_DDR.xdc

# Block Designs: bd/design_2/design_2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_design_1_0_0/design_2_design_1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_design_1_0_0 || ORIG_REF_NAME==design_2_design_1_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_design_1_1_0/design_2_design_1_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_design_1_1_0 || ORIG_REF_NAME==design_2_design_1_1_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_design_1_1_1/design_2_design_1_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_design_1_1_1 || ORIG_REF_NAME==design_2_design_1_1_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_design_1_1_2/design_2_design_1_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_design_1_1_2 || ORIG_REF_NAME==design_2_design_1_1_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xup_xor2_0_0/design_2_xup_xor2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xup_xor2_0_0 || ORIG_REF_NAME==design_2_xup_xor2_0_0} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xup_xor2_0_1/design_2_xup_xor2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xup_xor2_0_1 || ORIG_REF_NAME==design_2_xup_xor2_0_1} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xup_xor2_0_2/design_2_xup_xor2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xup_xor2_0_2 || ORIG_REF_NAME==design_2_xup_xor2_0_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xup_xor2_0_3/design_2_xup_xor2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xup_xor2_0_3 || ORIG_REF_NAME==design_2_xup_xor2_0_3} -quiet] -quiet

# IP: bd/design_2/ip/design_2_xup_xor2_0_4/design_2_xup_xor2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_2_xup_xor2_0_4 || ORIG_REF_NAME==design_2_xup_xor2_0_4} -quiet] -quiet

# XDC: bd/design_2/design_2_ooc.xdc
